In [96]:
import pandas as pd
import numpy as np

In [97]:
file_path = '/content/drive/MyDrive/FakeNewsDataset/train.csv'

In [98]:
df = pd.read_csv(file_path)

In [99]:
df.head(10)

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1
5   5  ...     0
6   6  ...     1
7   7  ...     0
8   8  ...     0
9   9  ...     0

[10 rows x 5 columns]

In [100]:
x = df.drop('label', axis=1)

In [101]:
x.head()

id  ...                                               text
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 4 columns]

In [102]:
df.shape

(20800, 5)

In [103]:
df = df.dropna()

In [104]:
df.head(10)

id  ... label
0    0  ...     1
1    1  ...     0
2    2  ...     1
3    3  ...     1
4    4  ...     1
5    5  ...     0
7    7  ...     0
9    9  ...     0
10  10  ...     0
11  11  ...     0

[10 rows x 5 columns]

In [105]:
df.shape

(18285, 5)

In [106]:
message = df.copy()

In [107]:
message.reset_index(inplace=True)

In [108]:
message.head(10)

index  id  ...                                               text label
0      0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...     1
1      1   1  ...  Ever get the feeling your life circles the rou...     0
2      2   2  ...  Why the Truth Might Get You Fired October 29, ...     1
3      3   3  ...  Videos 15 Civilians Killed In Single US Airstr...     1
4      4   4  ...  Print \nAn Iranian woman has been sentenced to...     1
5      5   5  ...  In these trying times, Jackie Mason is the Voi...     0
6      7   7  ...  PARIS  —   France chose an idealistic, traditi...     0
7      9   9  ...  A week before Michael T. Flynn resigned as nat...     0
8     10  10  ...  Organizing for Action, the activist group that...     0
9     11  11  ...  The BBC produced spoof on the “Real Housewives...     0

[10 rows x 6 columns]

In [109]:
y = message['label']
y.head(10)

0    1
1    0
2    1
3    1
4    1
5    0
6    0
7    0
8    0
9    0
Name: label, dtype: int64

In [110]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

In [111]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [112]:
ps = PorterStemmer()
corpus = []

In [113]:
for i in range(0, len(message)):
  msg = message['title'][i]
  review = re.sub('[^a-zA-z]', ' ', msg)
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [114]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic [photos]',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hi

In [115]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [116]:
voc_size = 5000

#One Hot Encoding

In [117]:
onehot_en = [one_hot(words, voc_size) for words in corpus]
print(onehot_en)

[[3155, 2098, 1896, 2010, 3732, 3178, 3265, 3237, 3039, 4497], [380, 2614, 2323, 2016, 1571, 670, 4474], [1893, 4977, 2776, 3138], [4499, 2944, 1225, 4808, 420, 1303], [4236, 1571, 2517, 3849, 3571, 1020, 1571, 3944, 1322, 1826], [574, 384, 2292, 1867, 1391, 1224, 4552, 4111, 3783, 2496, 511, 802, 3129, 95, 4474], [1630, 3515, 335, 2612, 4949, 4545, 1092, 1535, 908, 176, 1311], [4923, 2997, 2193, 4422, 687, 4417, 1224, 1239, 908, 176, 1311], [1069, 1560, 3987, 879, 2919, 1029, 3023, 3387, 1224, 3007], [1958, 3854, 1322, 4260, 2132, 885, 2184, 1394], [1142, 4626, 3326, 2601, 822, 4708, 4118, 4067, 444, 187, 357], [4808, 734, 3732, 1029, 1224, 687], [548, 3191, 2203, 1551, 1824, 2991, 340, 4446, 4709], [3607, 3067, 3561, 34, 304, 2746, 4226, 908, 176, 1311], [2575, 879, 4215, 1037, 1732, 908, 176, 1311], [1740, 4119, 4108, 262, 4534, 636, 3118, 1676, 4896, 1728], [730, 4169, 2614], [2519, 4720, 3390, 2639, 1224, 163, 960, 4474], [2728, 4079, 2323, 2905, 4342, 4898, 1129, 1812, 1020], [30

In [118]:
for i in range(4):
  print("Corpus: "+corpus[i])
  print("One Hot Encoding: "+str(onehot_en[i]))

Corpus: hous dem aid even see comey letter jason chaffetz tweet
One Hot Encoding: [3155, 2098, 1896, 2010, 3732, 3178, 3265, 3237, 3039, 4497]
Corpus: flynn hillari clinton big woman campu breitbart
One Hot Encoding: [380, 2614, 2323, 2016, 1571, 670, 4474]
Corpus: truth might get fire
One Hot Encoding: [1893, 4977, 2776, 3138]
Corpus: civilian kill singl us airstrik identifi
One Hot Encoding: [4499, 2944, 1225, 4808, 420, 1303]


In [119]:
sent_len = 20
embedded_rpre = pad_sequences(onehot_en, padding='pre', maxlen=sent_len)
print(embedded_rpre)

[[   0    0    0 ... 3237 3039 4497]
 [   0    0    0 ... 1571  670 4474]
 [   0    0    0 ... 4977 2776 3138]
 ...
 [   0    0    0 ...  908  176 1311]
 [   0    0    0 ... 2951 3343 4546]
 [   0    0    0 ... 3805 4805 3327]]


In [120]:
print(embedded_rpre[0])

[   0    0    0    0    0    0    0    0    0    0 3155 2098 1896 2010
 3732 3178 3265 3237 3039 4497]


In [155]:
embedding_vector_fetures = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_fetures, input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_12 (Embedding)     (None, 20, 40)            200000    
_________________________________________________________________
lstm_10 (LSTM)               (None, 100)               56400     
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [156]:
x_final = np.array(embedded_rpre)
y_final = np.array(y)

In [157]:
from sklearn.model_selection import train_test_split

In [158]:
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size = 0.33, random_state = 42)

In [159]:
model.fit(x_train, y_train, validation_data=(x_test, y_test),epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 39ms/step - loss: 0.3454 - accuracy: 0.8345 - val_loss: 0.2006 - val_accuracy: 0.9181
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1387 - accuracy: 0.9464 - val_loss: 0.1979 - val_accuracy: 0.9167
Epoch 3/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0967 - accuracy: 0.9660 - val_loss: 0.2175 - val_accuracy: 0.9147
Epoch 4/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0647 - accuracy: 0.9785 - val_loss: 0.2591 - val_accuracy: 0.9138
Epoch 5/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0419 - accuracy: 0.9865 - val_loss: 0.3100 - val_accuracy: 0.9137
Epoch 6/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0282 - accuracy: 0.9912 - val_loss: 0.3281 - val_accuracy: 0.9117
Epoch 7/10
192/192 [==============================] - 7s 37ms/step - loss: 0.0137 - accuracy: 0.9962 - val_loss: 0.3885 - val_accuracy: 0.9100

#Adding Dropout

In [147]:
embedding_vector_fetures = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_fetures, input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_11 (Embedding)     (None, 20, 40)            200000    
_________________________________________________________________
lstm_9 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


#Confusion Matrix and Accuracy

In [160]:
y_preds = model.predict(x_test)

In [161]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [162]:
y_preds = (y_preds>0.5)

In [163]:
print(y_preds[0:10])

[[ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [ True]
 [ True]]


In [164]:
y_test[0:10]

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 1])

In [165]:
cm = confusion_matrix(y_test, y_preds)
print(cm)

[[3058  361]
 [ 138 2478]]


In [166]:
ac_score = accuracy_score(y_test, y_preds)
print(ac_score)

0.9173156586578294
