In [4]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [10]:
sentence = ['the glass of milk',
            'the glass of juice',
            'the cup of tea',
            'i am good boy',
            'i am a good developer',
            'understading the meaning of words',
            'something is better then nothing']

In [11]:
sentence

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am good boy',
 'i am a good developer',
 'understading the meaning of words',
 'something is better then nothing']

In [12]:
voc_size = 10000

In [13]:
onehot_sen = [one_hot(word, voc_size) for word in sentence]
print(onehot_sen)

[[2500, 1454, 7562, 1138], [2500, 1454, 7562, 4376], [2500, 2129, 7562, 4296], [7027, 3330, 7481, 9623], [7027, 3330, 9113, 7481, 3213], [4619, 2500, 844, 7562, 8119], [9536, 6449, 441, 7729, 5442]]


In [20]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.models import Sequential

In [21]:
sentence_len = 8
embedded_text = pad_sequences(onehot_sen, padding='pre', maxlen=sentence_len)
print(embedded_text)

[[   0    0    0    0 2500 1454 7562 1138]
 [   0    0    0    0 2500 1454 7562 4376]
 [   0    0    0    0 2500 2129 7562 4296]
 [   0    0    0    0 7027 3330 7481 9623]
 [   0    0    0 7027 3330 9113 7481 3213]
 [   0    0    0 4619 2500  844 7562 8119]
 [   0    0    0 9536 6449  441 7729 5442]]


In [24]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sentence_len))
model.compile('adam', 'mse')

In [27]:
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________
None


In [28]:
print(embedded_text[0])

[   0    0    0    0 2500 1454 7562 1138]


In [31]:
print(model.predict(embedded_text)[0])

[[-0.00684625 -0.00598665 -0.04020643  0.04558152  0.03530283 -0.0371871
  -0.03830656 -0.00085992 -0.02998296  0.00207298]
 [-0.00684625 -0.00598665 -0.04020643  0.04558152  0.03530283 -0.0371871
  -0.03830656 -0.00085992 -0.02998296  0.00207298]
 [-0.00684625 -0.00598665 -0.04020643  0.04558152  0.03530283 -0.0371871
  -0.03830656 -0.00085992 -0.02998296  0.00207298]
 [-0.00684625 -0.00598665 -0.04020643  0.04558152  0.03530283 -0.0371871
  -0.03830656 -0.00085992 -0.02998296  0.00207298]
 [ 0.02770772 -0.00062523 -0.00684793  0.01461253  0.0392215   0.0202418
  -0.03908168 -0.04059815  0.04035744 -0.01161725]
 [ 0.00379612 -0.00335474 -0.01745012 -0.0039207   0.03854996 -0.02964727
   0.03025636  0.01266732 -0.01584222  0.00798702]
 [ 0.02392362  0.0190067  -0.02492837  0.04858949 -0.01864289  0.00218151
  -0.00712043  0.01498095  0.02783621 -0.01591346]
 [ 0.04309716 -0.00673491 -0.03299004 -0.0314216   0.04305798  0.00111929
   0.04940869  0.00504469 -0.0142943   0.00779178]]
